language: csharp
mono: none
dotnet: 2.1
script:
 - dotnet build nuget/osn-i18n.csproj && dotnet pack nuget/osn-i18n.csproj && dotnet nuget push nuget/bin/Debug/*.nupkg -s https://api.nuget.org/v3/index.json -k $nuget_key