language: csharp
mono: none
dotnet: 2.1
install:
  - nvm install 8.0.0
  - nvm use 8.0.0
  - npm install
  - dotnet restore nuget/osn-i18n.csproj

jobs:
  include:
    - stage: dotnet build release
      script:
        - dotnet build nuget/osn-i18n.csproj
        - dotnet nuget push nuget/bin/Debug/*.nupkg -s https://api.nuget.org/v3/index.json -k $nuget_key
    - stage: npm release
      node_js: "8"
      script: 
        - echo "Deploying to npm ..."
        - npm version patch --force
      deploy:
        provider: npm
        email: "jaylandro@gmail.com"
        api_key: $npm_key
        on:
          branch: master