language: csharp
mono: none
dotnet: 2.1
install:
  - nvm install 8.0.0
  - nvm use 8.0.0
  - npm install
script:
  - dotnet build nuget/osn-i18n.csproj
  - dotnet pack nuget/osn-i18n.csproj
  - dotnet nuget push nuget/bin/Debug/*.nupkg -s https://api.nuget.org/v3/index.json -k $nuget_key
  - npm version patch --force
deploy:  
  provider: npm
  email: "jaylandro@gmail.com"
  api_key:
    secure: $npm_key
    tags: true
  on:
    branch: master