using System.Collections.Generic;

namespace OsnI18n
{
	// THANK U RACHEL @ https://www.rachelfrantsen.com (Dotnet represent!!)

	public class Country {
		public string Code { get; set; }
		public string Name { get; set; }
		public string Native { get; set; }
		public string Phone { get; set; }
		public string Continent { get; set; }
		public string Capital { get; set; }
		public string Currency { get; set; }
		public IEnumerable<string> Languages { get; set; }

		public Country(string code, string name, string native, string phone, string continent, string capital, string currency, IEnumerable<string> languages) {
			Code = code;
			Name = name;
			Native = native;
			Phone = phone;
			Continent = continent;
			Capital = capital;
			Currency = currency;
			Languages = languages;
		}
	}

public static class CountryData {
	public static IEnumerable<Country> Countries = new List<Country>()
	{
	 new Country("AD", "Andorra", "Andorra", "376", "EU", "Andorra la Vella", "EUR", new List<string>()),
	 new Country("AE", "United Arab Emirates", "دولة الإمارات العربية المتحدة", "971", "AS", "Abu Dhabi", "AED", new List<string>()),
	 new Country("AF", "Afghanistan", "افغانستان", "93", "AS", "Kabul", "AFN", new List<string>()),
	 new Country("AG", "Antigua and Barbuda", "Antigua and Barbuda", "1268", "NA", "Saint John's", "XCD", new List<string>()),
	 new Country("AI", "Anguilla", "Anguilla", "1264", "NA", "The Valley", "XCD", new List<string>()),
	 new Country("AL", "Albania", "Shqipëria", "355", "EU", "Tirana", "ALL", new List<string>()),
	 new Country("AM", "Armenia", "Հայաստան", "374", "AS", "Yerevan", "AMD", new List<string>()),
	 new Country("AO", "Angola", "Angola", "244", "AF", "Luanda", "AOA", new List<string>()),
	 new Country("AQ", "Antarctica", "Antarctica", "672", "AN", "", "", new List<string>()),
	 new Country("AR", "Argentina", "Argentina", "54", "SA", "Buenos Aires", "ARS", new List<string>()),
	 new Country("AS", "American Samoa", "American Samoa", "1684", "OC", "Pago Pago", "USD", new List<string>()),
	 new Country("AT", "Austria", "Österreich", "43", "EU", "Vienna", "EUR", new List<string>()),
	 new Country("AU", "Australia", "Australia", "61", "OC", "Canberra", "AUD", new List<string>()),
	 new Country("AW", "Aruba", "Aruba", "297", "NA", "Oranjestad", "AWG", new List<string>()),
	 new Country("AX", "Åland", "Åland", "358", "EU", "Mariehamn", "EUR", new List<string>()),
	 new Country("AZ", "Azerbaijan", "Azərbaycan", "994", "AS", "Baku", "AZN", new List<string>()),
	 new Country("BA", "Bosnia and Herzegovina", "Bosna i Hercegovina", "387", "EU", "Sarajevo", "BAM", new List<string>()),
	 new Country("BB", "Barbados", "Barbados", "1246", "NA", "Bridgetown", "BBD", new List<string>()),
	 new Country("BD", "Bangladesh", "Bangladesh", "880", "AS", "Dhaka", "BDT", new List<string>()),
	 new Country("BE", "Belgium", "België", "32", "EU", "Brussels", "EUR", new List<string>()),
	 new Country("BF", "Burkina Faso", "Burkina Faso", "226", "AF", "Ouagadougou", "XOF", new List<string>()),
	 new Country("BG", "Bulgaria", "България", "359", "EU", "Sofia", "BGN", new List<string>()),
	 new Country("BH", "Bahrain", "‏البحرين", "973", "AS", "Manama", "BHD", new List<string>()),
	 new Country("BI", "Burundi", "Burundi", "257", "AF", "Bujumbura", "BIF", new List<string>()),
	 new Country("BJ", "Benin", "Bénin", "229", "AF", "Porto-Novo", "XOF", new List<string>()),
	 new Country("BL", "Saint Barthélemy", "Saint-Barthélemy", "590", "NA", "Gustavia", "EUR", new List<string>()),
	 new Country("BM", "Bermuda", "Bermuda", "1441", "NA", "Hamilton", "BMD", new List<string>()),
	 new Country("BN", "Brunei", "Negara Brunei Darussalam", "673", "AS", "Bandar Seri Begawan", "BND", new List<string>()),
	 new Country("BO", "Bolivia", "Bolivia", "591", "SA", "Sucre", "BOB,BOV", new List<string>()),
	 new Country("BQ", "Bonaire", "Bonaire", "5997", "NA", "Kralendijk", "USD", new List<string>()),
	 new Country("BR", "Brazil", "Brasil", "55", "SA", "Brasília", "BRL", new List<string>()),
	 new Country("BS", "Bahamas", "Bahamas", "1242", "NA", "Nassau", "BSD", new List<string>()),
	 new Country("BT", "Bhutan", "ʼbrug-yul", "975", "AS", "Thimphu", "BTN,INR", new List<string>()),
	 new Country("BV", "Bouvet Island", "Bouvetøya", "47", "AN", "", "NOK", new List<string>()),
	 new Country("BW", "Botswana", "Botswana", "267", "AF", "Gaborone", "BWP", new List<string>()),
	 new Country("BY", "Belarus", "Белару́сь", "375", "EU", "Minsk", "BYR", new List<string>()),
	 new Country("BZ", "Belize", "Belize", "501", "NA", "Belmopan", "BZD", new List<string>()),
	 new Country("CA", "Canada", "Canada", "1", "NA", "Ottawa", "CAD", new List<string>()),
	 new Country("CC", "Cocos [Keeling] Islands", "Cocos (Keeling) Islands", "61", "AS", "West Island", "AUD", new List<string>()),
	 new Country("CD", "Democratic Republic of the Congo", "République démocratique du Congo", "243", "AF", "Kinshasa", "CDF", new List<string>()),
	 new Country("CF", "Central African Republic", "Ködörösêse tî Bêafrîka", "236", "AF", "Bangui", "XAF", new List<string>()),
	 new Country("CG", "Republic of the Congo", "République du Congo", "242", "AF", "Brazzaville", "XAF", new List<string>()),
	 new Country("CH", "Switzerland", "Schweiz", "41", "EU", "Bern", "CHE,CHF,CHW", new List<string>()),
	 new Country("CI", "Ivory Coast", "Côte d'Ivoire", "225", "AF", "Yamoussoukro", "XOF", new List<string>()),
	 new Country("CK", "Cook Islands", "Cook Islands", "682", "OC", "Avarua", "NZD", new List<string>()),
	 new Country("CL", "Chile", "Chile", "56", "SA", "Santiago", "CLF,CLP", new List<string>()),
	 new Country("CM", "Cameroon", "Cameroon", "237", "AF", "Yaoundé", "XAF", new List<string>()),
	 new Country("CN", "China", "中国", "86", "AS", "Beijing", "CNY", new List<string>()),
	 new Country("CO", "Colombia", "Colombia", "57", "SA", "Bogotá", "COP", new List<string>()),
	 new Country("CR", "Costa Rica", "Costa Rica", "506", "NA", "San José", "CRC", new List<string>()),
	 new Country("CU", "Cuba", "Cuba", "53", "NA", "Havana", "CUC,CUP", new List<string>()),
	 new Country("CV", "Cape Verde", "Cabo Verde", "238", "AF", "Praia", "CVE", new List<string>()),
	 new Country("CW", "Curacao", "Curaçao", "5999", "NA", "Willemstad", "ANG", new List<string>()),
	 new Country("CX", "Christmas Island", "Christmas Island", "61", "AS", "Flying Fish Cove", "AUD", new List<string>()),
	 new Country("CY", "Cyprus", "Κύπρος", "357", "EU", "Nicosia", "EUR", new List<string>()),
	 new Country("CZ", "Czech Republic", "Česká republika", "420", "EU", "Prague", "CZK", new List<string>()),
	 new Country("DE", "Germany", "Deutschland", "49", "EU", "Berlin", "EUR", new List<string>()),
	 new Country("DJ", "Djibouti", "Djibouti", "253", "AF", "Djibouti", "DJF", new List<string>()),
	 new Country("DK", "Denmark", "Danmark", "45", "EU", "Copenhagen", "DKK", new List<string>()),
	 new Country("DM", "Dominica", "Dominica", "1767", "NA", "Roseau", "XCD", new List<string>()),
	 new Country("DO", "Dominican Republic", "República Dominicana", "1809,1829,1849", "NA", "Santo Domingo", "DOP", new List<string>()),
	 new Country("DZ", "Algeria", "الجزائر", "213", "AF", "Algiers", "DZD", new List<string>()),
	 new Country("EC", "Ecuador", "Ecuador", "593", "SA", "Quito", "USD", new List<string>()),
	 new Country("EE", "Estonia", "Eesti", "372", "EU", "Tallinn", "EUR", new List<string>()),
	 new Country("EG", "Egypt", "مصر‎", "20", "AF", "Cairo", "EGP", new List<string>()),
	 new Country("EH", "Western Sahara", "الصحراء الغربية", "212", "AF", "El Aaiún", "MAD,DZD,MRU", new List<string>()),
	 new Country("ER", "Eritrea", "ኤርትራ", "291", "AF", "Asmara", "ERN", new List<string>()),
	 new Country("ES", "Spain", "España", "34", "EU", "Madrid", "EUR", new List<string>()),
	 new Country("ET", "Ethiopia", "ኢትዮጵያ", "251", "AF", "Addis Ababa", "ETB", new List<string>()),
	 new Country("FI", "Finland", "Suomi", "358", "EU", "Helsinki", "EUR", new List<string>()),
	 new Country("FJ", "Fiji", "Fiji", "679", "OC", "Suva", "FJD", new List<string>()),
	 new Country("FK", "Falkland Islands", "Falkland Islands", "500", "SA", "Stanley", "FKP", new List<string>()),
	 new Country("FM", "Micronesia", "Micronesia", "691", "OC", "Palikir", "USD", new List<string>()),
	 new Country("FO", "Faroe Islands", "Føroyar", "298", "EU", "Tórshavn", "DKK", new List<string>()),
	 new Country("FR", "France", "France", "33", "EU", "Paris", "EUR", new List<string>()),
	 new Country("GA", "Gabon", "Gabon", "241", "AF", "Libreville", "XAF", new List<string>()),
	 new Country("GB", "United Kingdom", "United Kingdom", "44", "EU", "London", "GBP", new List<string>()),
	 new Country("GD", "Grenada", "Grenada", "1473", "NA", "St. George's", "XCD", new List<string>()),
	 new Country("GE", "Georgia", "საქართველო", "995", "AS", "Tbilisi", "GEL", new List<string>()),
	 new Country("GF", "French Guiana", "Guyane française", "594", "SA", "Cayenne", "EUR", new List<string>()),
	 new Country("GG", "Guernsey", "Guernsey", "44", "EU", "St. Peter Port", "GBP", new List<string>()),
	 new Country("GH", "Ghana", "Ghana", "233", "AF", "Accra", "GHS", new List<string>()),
	 new Country("GI", "Gibraltar", "Gibraltar", "350", "EU", "Gibraltar", "GIP", new List<string>()),
	 new Country("GL", "Greenland", "Kalaallit Nunaat", "299", "NA", "Nuuk", "DKK", new List<string>()),
	 new Country("GM", "Gambia", "Gambia", "220", "AF", "Banjul", "GMD", new List<string>()),
	 new Country("GN", "Guinea", "Guinée", "224", "AF", "Conakry", "GNF", new List<string>()),
	 new Country("GP", "Guadeloupe", "Guadeloupe", "590", "NA", "Basse-Terre", "EUR", new List<string>()),
	 new Country("GQ", "Equatorial Guinea", "Guinea Ecuatorial", "240", "AF", "Malabo", "XAF", new List<string>()),
	 new Country("GR", "Greece", "Ελλάδα", "30", "EU", "Athens", "EUR", new List<string>()),
	 new Country("GS", "South Georgia and the South Sandwich Islands", "South Georgia", "500", "AN", "King Edward Point", "GBP", new List<string>()),
	 new Country("GT", "Guatemala", "Guatemala", "502", "NA", "Guatemala City", "GTQ", new List<string>()),
	 new Country("GU", "Guam", "Guam", "1671", "OC", "Hagåtña", "USD", new List<string>()),
	 new Country("GW", "Guinea-Bissau", "Guiné-Bissau", "245", "AF", "Bissau", "XOF", new List<string>()),
	 new Country("GY", "Guyana", "Guyana", "592", "SA", "Georgetown", "GYD", new List<string>()),
	 new Country("HK", "Hong Kong", "香港", "852", "AS", "City of Victoria", "HKD", new List<string>()),
	 new Country("HM", "Heard Island and McDonald Islands", "Heard Island and McDonald Islands", "61", "AN", "", "AUD", new List<string>()),
	 new Country("HN", "Honduras", "Honduras", "504", "NA", "Tegucigalpa", "HNL", new List<string>()),
	 new Country("HR", "Croatia", "Hrvatska", "385", "EU", "Zagreb", "HRK", new List<string>()),
	 new Country("HT", "Haiti", "Haïti", "509", "NA", "Port-au-Prince", "HTG,USD", new List<string>()),
	 new Country("HU", "Hungary", "Magyarország", "36", "EU", "Budapest", "HUF", new List<string>()),
	 new Country("ID", "Indonesia", "Indonesia", "62", "AS", "Jakarta", "IDR", new List<string>()),
	 new Country("IE", "Ireland", "Éire", "353", "EU", "Dublin", "EUR", new List<string>()),
	 new Country("IL", "Israel", "יִשְׂרָאֵל", "972", "AS", "Jerusalem", "ILS", new List<string>()),
	 new Country("IM", "Isle of Man", "Isle of Man", "44", "EU", "Douglas", "GBP", new List<string>()),
	 new Country("IN", "India", "भारत", "91", "AS", "New Delhi", "INR", new List<string>()),
	 new Country("IO", "British Indian Ocean Territory", "British Indian Ocean Territory", "246", "AS", "Diego Garcia", "USD", new List<string>()),
	 new Country("IQ", "Iraq", "العراق", "964", "AS", "Baghdad", "IQD", new List<string>()),
	 new Country("IR", "Iran", "ایران", "98", "AS", "Tehran", "IRR", new List<string>()),
	 new Country("IS", "Iceland", "Ísland", "354", "EU", "Reykjavik", "ISK", new List<string>()),
	 new Country("IT", "Italy", "Italia", "39", "EU", "Rome", "EUR", new List<string>()),
	 new Country("JE", "Jersey", "Jersey", "44", "EU", "Saint Helier", "GBP", new List<string>()),
	 new Country("JM", "Jamaica", "Jamaica", "1876", "NA", "Kingston", "JMD", new List<string>()),
	 new Country("JO", "Jordan", "الأردن", "962", "AS", "Amman", "JOD", new List<string>()),
	 new Country("JP", "Japan", "日本", "81", "AS", "Tokyo", "JPY", new List<string>()),
	 new Country("KE", "Kenya", "Kenya", "254", "AF", "Nairobi", "KES", new List<string>()),
	 new Country("KG", "Kyrgyzstan", "Кыргызстан", "996", "AS", "Bishkek", "KGS", new List<string>()),
	 new Country("KH", "Cambodia", "Kâmpŭchéa", "855", "AS", "Phnom Penh", "KHR", new List<string>()),
	 new Country("KI", "Kiribati", "Kiribati", "686", "OC", "South Tarawa", "AUD", new List<string>()),
	 new Country("KM", "Comoros", "Komori", "269", "AF", "Moroni", "KMF", new List<string>()),
	 new Country("KN", "Saint Kitts and Nevis", "Saint Kitts and Nevis", "1869", "NA", "Basseterre", "XCD", new List<string>()),
	 new Country("KP", "North Korea", "북한", "850", "AS", "Pyongyang", "KPW", new List<string>()),
	 new Country("KR", "South Korea", "대한민국", "82", "AS", "Seoul", "KRW", new List<string>()),
	 new Country("KW", "Kuwait", "الكويت", "965", "AS", "Kuwait City", "KWD", new List<string>()),
	 new Country("KY", "Cayman Islands", "Cayman Islands", "1345", "NA", "George Town", "KYD", new List<string>()),
	 new Country("KZ", "Kazakhstan", "Қазақстан", "76,77", "AS", "Astana", "KZT", new List<string>()),
	 new Country("LA", "Laos", "ສປປລາວ", "856", "AS", "Vientiane", "LAK", new List<string>()),
	 new Country("LB", "Lebanon", "لبنان", "961", "AS", "Beirut", "LBP", new List<string>()),
	 new Country("LC", "Saint Lucia", "Saint Lucia", "1758", "NA", "Castries", "XCD", new List<string>()),
	 new Country("LI", "Liechtenstein", "Liechtenstein", "423", "EU", "Vaduz", "CHF", new List<string>()),
	 new Country("LK", "Sri Lanka", "śrī laṃkāva", "94", "AS", "Colombo", "LKR", new List<string>()),
	 new Country("LR", "Liberia", "Liberia", "231", "AF", "Monrovia", "LRD", new List<string>()),
	 new Country("LS", "Lesotho", "Lesotho", "266", "AF", "Maseru", "LSL,ZAR", new List<string>()),
	 new Country("LT", "Lithuania", "Lietuva", "370", "EU", "Vilnius", "EUR", new List<string>()),
	 new Country("LU", "Luxembourg", "Luxembourg", "352", "EU", "Luxembourg", "EUR", new List<string>()),
	 new Country("LV", "Latvia", "Latvija", "371", "EU", "Riga", "EUR", new List<string>()),
	 new Country("LY", "Libya", "‏ليبيا", "218", "AF", "Tripoli", "LYD", new List<string>()),
	 new Country("MA", "Morocco", "المغرب", "212", "AF", "Rabat", "MAD", new List<string>()),
	 new Country("MC", "Monaco", "Monaco", "377", "EU", "Monaco", "EUR", new List<string>()),
	 new Country("MD", "Moldova", "Moldova", "373", "EU", "Chișinău", "MDL", new List<string>()),
	 new Country("ME", "Montenegro", "Црна Гора", "382", "EU", "Podgorica", "EUR", new List<string>()),
	 new Country("MF", "Saint Martin", "Saint-Martin", "590", "NA", "Marigot", "EUR", new List<string>()),
	 new Country("MG", "Madagascar", "Madagasikara", "261", "AF", "Antananarivo", "MGA", new List<string>()),
	 new Country("MH", "Marshall Islands", "M̧ajeļ", "692", "OC", "Majuro", "USD", new List<string>()),
	 new Country("MK", "Macedonia", "Македонија", "389", "EU", "Skopje", "MKD", new List<string>()),
	 new Country("ML", "Mali", "Mali", "223", "AF", "Bamako", "XOF", new List<string>()),
	 new Country("MM", "Myanmar [Burma]", "မြန်မာ", "95", "AS", "Naypyidaw", "MMK", new List<string>()),
	 new Country("MN", "Mongolia", "Монгол улс", "976", "AS", "Ulan Bator", "MNT", new List<string>()),
	 new Country("MO", "Macao", "澳門", "853", "AS", "", "MOP", new List<string>()),
	 new Country("MP", "Northern Mariana Islands", "Northern Mariana Islands", "1670", "OC", "Saipan", "USD", new List<string>()),
	 new Country("MQ", "Martinique", "Martinique", "596", "NA", "Fort-de-France", "EUR", new List<string>()),
	 new Country("MR", "Mauritania", "موريتانيا", "222", "AF", "Nouakchott", "MRU", new List<string>()),
	 new Country("MS", "Montserrat", "Montserrat", "1664", "NA", "Plymouth", "XCD", new List<string>()),
	 new Country("MT", "Malta", "Malta", "356", "EU", "Valletta", "EUR", new List<string>()),
	 new Country("MU", "Mauritius", "Maurice", "230", "AF", "Port Louis", "MUR", new List<string>()),
	 new Country("MV", "Maldives", "Maldives", "960", "AS", "Malé", "MVR", new List<string>()),
	 new Country("MW", "Malawi", "Malawi", "265", "AF", "Lilongwe", "MWK", new List<string>()),
	 new Country("MX", "Mexico", "México", "52", "NA", "Mexico City", "MXN", new List<string>()),
	 new Country("MY", "Malaysia", "Malaysia", "60", "AS", "Kuala Lumpur", "MYR", new List<string>()),
	 new Country("MZ", "Mozambique", "Moçambique", "258", "AF", "Maputo", "MZN", new List<string>()),
	 new Country("NA", "Namibia", "Namibia", "264", "AF", "Windhoek", "NAD,ZAR", new List<string>()),
	 new Country("NC", "New Caledonia", "Nouvelle-Calédonie", "687", "OC", "Nouméa", "XPF", new List<string>()),
	 new Country("NE", "Niger", "Niger", "227", "AF", "Niamey", "XOF", new List<string>()),
	 new Country("NF", "Norfolk Island", "Norfolk Island", "672", "OC", "Kingston", "AUD", new List<string>()),
	 new Country("NG", "Nigeria", "Nigeria", "234", "AF", "Abuja", "NGN", new List<string>()),
	 new Country("NI", "Nicaragua", "Nicaragua", "505", "NA", "Managua", "NIO", new List<string>()),
	 new Country("NL", "Netherlands", "Nederland", "31", "EU", "Amsterdam", "EUR", new List<string>()),
	 new Country("NO", "Norway", "Norge", "47", "EU", "Oslo", "NOK", new List<string>()),
	 new Country("NP", "Nepal", "नपल", "977", "AS", "Kathmandu", "NPR", new List<string>()),
	 new Country("NR", "Nauru", "Nauru", "674", "OC", "Yaren", "AUD", new List<string>()),
	 new Country("NU", "Niue", "Niuē", "683", "OC", "Alofi", "NZD", new List<string>()),
	 new Country("NZ", "New Zealand", "New Zealand", "64", "OC", "Wellington", "NZD", new List<string>()),
	 new Country("OM", "Oman", "عمان", "968", "AS", "Muscat", "OMR", new List<string>()),
	 new Country("PA", "Panama", "Panamá", "507", "NA", "Panama City", "PAB,USD", new List<string>()),
	 new Country("PE", "Peru", "Perú", "51", "SA", "Lima", "PEN", new List<string>()),
	 new Country("PF", "French Polynesia", "Polynésie française", "689", "OC", "Papeetē", "XPF", new List<string>()),
	 new Country("PG", "Papua New Guinea", "Papua Niugini", "675", "OC", "Port Moresby", "PGK", new List<string>()),
	 new Country("PH", "Philippines", "Pilipinas", "63", "AS", "Manila", "PHP", new List<string>()),
	 new Country("PK", "Pakistan", "Pakistan", "92", "AS", "Islamabad", "PKR", new List<string>()),
	 new Country("PL", "Poland", "Polska", "48", "EU", "Warsaw", "PLN", new List<string>()),
	 new Country("PM", "Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon", "508", "NA", "Saint-Pierre", "EUR", new List<string>()),
	 new Country("PN", "Pitcairn Islands", "Pitcairn Islands", "64", "OC", "Adamstown", "NZD", new List<string>()),
	 new Country("PR", "Puerto Rico", "Puerto Rico", "1787,1939", "NA", "San Juan", "USD", new List<string>()),
	 new Country("PS", "Palestine", "فلسطين", "970", "AS", "Ramallah", "ILS", new List<string>()),
	 new Country("PT", "Portugal", "Portugal", "351", "EU", "Lisbon", "EUR", new List<string>()),
	 new Country("PW", "Palau", "Palau", "680", "OC", "Ngerulmud", "USD", new List<string>()),
	 new Country("PY", "Paraguay", "Paraguay", "595", "SA", "Asunción", "PYG", new List<string>()),
	 new Country("QA", "Qatar", "قطر", "974", "AS", "Doha", "QAR", new List<string>()),
	 new Country("RE", "Réunion", "La Réunion", "262", "AF", "Saint-Denis", "EUR", new List<string>()),
	 new Country("RO", "Romania", "România", "40", "EU", "Bucharest", "RON", new List<string>()),
	 new Country("RS", "Serbia", "Србија", "381", "EU", "Belgrade", "RSD", new List<string>()),
	 new Country("RU", "Russia", "Россия", "7", "EU", "Moscow", "RUB", new List<string>()),
	 new Country("RW", "Rwanda", "Rwanda", "250", "AF", "Kigali", "RWF", new List<string>()),
	 new Country("SA", "Saudi Arabia", "العربية السعودية", "966", "AS", "Riyadh", "SAR", new List<string>()),
	 new Country("SB", "Solomon Islands", "Solomon Islands", "677", "OC", "Honiara", "SBD", new List<string>()),
	 new Country("SC", "Seychelles", "Seychelles", "248", "AF", "Victoria", "SCR", new List<string>()),
	 new Country("SD", "Sudan", "السودان", "249", "AF", "Khartoum", "SDG", new List<string>()),
	 new Country("SE", "Sweden", "Sverige", "46", "EU", "Stockholm", "SEK", new List<string>()),
	 new Country("SG", "Singapore", "Singapore", "65", "AS", "Singapore", "SGD", new List<string>()),
	 new Country("SH", "Saint Helena", "Saint Helena", "290", "AF", "Jamestown", "SHP", new List<string>()),
	 new Country("SI", "Slovenia", "Slovenija", "386", "EU", "Ljubljana", "EUR", new List<string>()),
	 new Country("SJ", "Svalbard and Jan Mayen", "Svalbard og Jan Mayen", "4779", "EU", "Longyearbyen", "NOK", new List<string>()),
	 new Country("SK", "Slovakia", "Slovensko", "421", "EU", "Bratislava", "EUR", new List<string>()),
	 new Country("SL", "Sierra Leone", "Sierra Leone", "232", "AF", "Freetown", "SLL", new List<string>()),
	 new Country("SM", "San Marino", "San Marino", "378", "EU", "City of San Marino", "EUR", new List<string>()),
	 new Country("SN", "Senegal", "Sénégal", "221", "AF", "Dakar", "XOF", new List<string>()),
	 new Country("SO", "Somalia", "Soomaaliya", "252", "AF", "Mogadishu", "SOS", new List<string>()),
	 new Country("SR", "Suriname", "Suriname", "597", "SA", "Paramaribo", "SRD", new List<string>()),
	 new Country("SS", "South Sudan", "South Sudan", "211", "AF", "Juba", "SSP", new List<string>()),
	 new Country("ST", "São Tomé and Príncipe", "São Tomé e Príncipe", "239", "AF", "São Tomé", "STN", new List<string>()),
	 new Country("SV", "El Salvador", "El Salvador", "503", "NA", "San Salvador", "SVC,USD", new List<string>()),
	 new Country("SX", "Sint Maarten", "Sint Maarten", "1721", "NA", "Philipsburg", "ANG", new List<string>()),
	 new Country("SY", "Syria", "سوريا", "963", "AS", "Damascus", "SYP", new List<string>()),
	 new Country("SZ", "Swaziland", "Swaziland", "268", "AF", "Lobamba", "SZL", new List<string>()),
	 new Country("TC", "Turks and Caicos Islands", "Turks and Caicos Islands", "1649", "NA", "Cockburn Town", "USD", new List<string>()),
	 new Country("TD", "Chad", "Tchad", "235", "AF", "N'Djamena", "XAF", new List<string>()),
	 new Country("TF", "French Southern Territories", "Territoire des Terres australes et antarctiques fr", "262", "AN", "Port-aux-Français", "EUR", new List<string>()),
	 new Country("TG", "Togo", "Togo", "228", "AF", "Lomé", "XOF", new List<string>()),
	 new Country("TH", "Thailand", "ประเทศไทย", "66", "AS", "Bangkok", "THB", new List<string>()),
	 new Country("TJ", "Tajikistan", "Тоҷикистон", "992", "AS", "Dushanbe", "TJS", new List<string>()),
	 new Country("TK", "Tokelau", "Tokelau", "690", "OC", "Fakaofo", "NZD", new List<string>()),
	 new Country("TL", "East Timor", "Timor-Leste", "670", "OC", "Dili", "USD", new List<string>()),
	 new Country("TM", "Turkmenistan", "Türkmenistan", "993", "AS", "Ashgabat", "TMT", new List<string>()),
	 new Country("TN", "Tunisia", "تونس", "216", "AF", "Tunis", "TND", new List<string>()),
	 new Country("TO", "Tonga", "Tonga", "676", "OC", "Nuku'alofa", "TOP", new List<string>()),
	 new Country("TR", "Turkey", "Türkiye", "90", "AS", "Ankara", "TRY", new List<string>()),
	 new Country("TT", "Trinidad and Tobago", "Trinidad and Tobago", "1868", "NA", "Port of Spain", "TTD", new List<string>()),
	 new Country("TV", "Tuvalu", "Tuvalu", "688", "OC", "Funafuti", "AUD", new List<string>()),
	 new Country("TW", "Taiwan", "臺灣", "886", "AS", "Taipei", "TWD", new List<string>()),
	 new Country("TZ", "Tanzania", "Tanzania", "255", "AF", "Dodoma", "TZS", new List<string>()),
	 new Country("UA", "Ukraine", "Україна", "380", "EU", "Kyiv", "UAH", new List<string>()),
	 new Country("UG", "Uganda", "Uganda", "256", "AF", "Kampala", "UGX", new List<string>()),
	 new Country("UM", "U.S. Minor Outlying Islands", "United States Minor Outlying Islands", "1", "OC", "", "USD", new List<string>()),
	 new Country("US", "United States", "United States", "1", "NA", "Washington D.C.", "USD,USN,USS", new List<string>()),
	 new Country("UY", "Uruguay", "Uruguay", "598", "SA", "Montevideo", "UYI,UYU", new List<string>()),
	 new Country("UZ", "Uzbekistan", "O‘zbekiston", "998", "AS", "Tashkent", "UZS", new List<string>()),
	 new Country("VA", "Vatican City", "Vaticano", "39066,379", "EU", "Vatican City", "EUR", new List<string>()),
	 new Country("VC", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", "1784", "NA", "Kingstown", "XCD", new List<string>()),
	 new Country("VE", "Venezuela", "Venezuela", "58", "SA", "Caracas", "VES", new List<string>()),
	 new Country("VG", "British Virgin Islands", "British Virgin Islands", "1284", "NA", "Road Town", "USD", new List<string>()),
	 new Country("VI", "U.S. Virgin Islands", "United States Virgin Islands", "1340", "NA", "Charlotte Amalie", "USD", new List<string>()),
	 new Country("VN", "Vietnam", "Việt Nam", "84", "AS", "Hanoi", "VND", new List<string>()),
	 new Country("VU", "Vanuatu", "Vanuatu", "678", "OC", "Port Vila", "VUV", new List<string>()),
	 new Country("WF", "Wallis and Futuna", "Wallis et Futuna", "681", "OC", "Mata-Utu", "XPF", new List<string>()),
	 new Country("WS", "Samoa", "Samoa", "685", "OC", "Apia", "WST", new List<string>()),
	 new Country("XK", "Kosovo", "Republika e Kosovës", "377,381,383,386", "EU", "Pristina", "EUR", new List<string>()),
	 new Country("YE", "Yemen", "اليَمَن", "967", "AS", "Sana'a", "YER", new List<string>()),
	 new Country("YT", "Mayotte", "Mayotte", "262", "AF", "Mamoudzou", "EUR", new List<string>()),
	 new Country("ZA", "South Africa", "South Africa", "27", "AF", "Pretoria", "ZAR", new List<string>()),
	 new Country("ZM", "Zambia", "Zambia", "260", "AF", "Lusaka", "ZMK", new List<string>()),
	 new Country("ZW", "Zimbabwe", "Zimbabwe", "263", "AF", "Harare", "USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY", new List<string>()),
	};
	}
}
